### ISSUE TITLE
Use a unique "Acmebot" useragent

### ISSUE THREAD

**Issue by cpu** [plinss/acmebot#1]
Hi there!

Thanks for writing an ACME client. I wanted to mention [Section 5.1 of ACME Draft-04](https://tools.ietf.org/html/draft-ietf-acme-acme-04#section-5.1):
>  ACME clients SHOULD send a User-Agent header in accordance with
>  [RFC7231], including the name and version of the ACME software in
>  addition to the name and version of the underlying HTTP client
>  software.

It doesn't look like `acmebot` is setting a UA right now, would you consider adding one? It certainly helps us from the server-side when we are troubleshooting client errors.

Thanks!

**Comment by plinss** [comment]
Glad to help out, and thanks for the suggestion. Let me know if there are any other changes you'd like to see.

**Comment by cpu** [comment]
Thanks @plinss !
