### ISSUE TITLE
Update to v2 ACME api

### ISSUE THREAD

**Issue by plinss** [plinss/acmebot#15]
Presumably this will mostly be handled by the acme library https://github.com/certbot/certbot/tree/master/acme

Tracking issue for potential api/behavior changes.

Also need to test wildcard certs.

**Comment by cpu** [comment]
@plinss You might be particularly interested in the [acme-v2](https://github.com/certbot/certbot/tree/acme-v2/acme) branch. It's not a completed work but the `chisel2` tool in that branch is using the starts of an updated `acme` module to test [Pebble](https://github.com/letsencrypt/pebble).

**Comment by plinss** [comment]
cool, thanks!

**Comment by OlafLostViking** [comment]
Oh, I just realized that we need v2 if we want wildcard certificates. Which we surely want, right? ;-)

**Comment by plinss** [comment]
Yes, absolutely. I'm just waiting for the v2 branch of acme to be generally available via pip (and for Let's Encrypt to be officially supporting it via the production url). Please feel free to ping this issue if I miss the release.

**Comment by aureq** [comment]
@plinss acme 0.22 is out and supports ACME v2 ;-) (hint hint)

**Comment by plinss** [comment]
Yep, I'm aware, was planning on spending some time on it tomorrow. (I need wildcard certs myself)

**Comment by aureq** [comment]
I've been trying to understand more about v2 (and v1), if you have time, it would be great is you could share some links so I (we) could better understand how the acme code is meant to be used (totally optional though).

Thanks a lot.

**Comment by plinss** [comment]
Fixed by 3bbc251008662dd35c98c793bf114c3d63df9f92

**Comment by plinss** [comment]
@aureq I don't really have the bandwidth to write much detail. But please feel free to use the acmebot code as guide. When learning it myself I used a combination of the [ACME spec](https://tools.ietf.org/html/draft-ietf-acme-acme-10), the [certbot acme library](https://github.com/certbot/certbot/tree/master/acme/acme) and how [certbot](https://github.com/certbot/certbot/blob/master/certbot/client.py) uses it. You'll also need to understand the [PyOpenSSL](https://pyopenssl.org/en/stable/) apis, and the Python [cryptography](https://cryptography.io/en/latest/) apis for cert and key handling.

Notably in acmebot search for calls to `self.acme_client` to see how it interacts with the acme api. It's used for initial registration, domain authorizations, issuing certificates, and revoking certificates. Also note that acmebot has a slightly different workflow when using the V2 api, in that it still performs pre-authorizations, even though the Let's Encrypt implementation of V2 doesn't support that (it's needed for the master/follower usage). acmebot creates it's own "authorization-only" certificate orders, which it then abandons, to perform pre-authorizations.

If you have specific questions, feel free to reach out.
