### ISSUE TITLE
Add deployment hooks

### ISSUE THREAD

**Issue by plinss** [plinss/acmebot#17]
It would be useful to be able to configure hooks that execute for given events, like certificate issued, key changed, oscp/sct updates, etc.

This would facilitate updating certificates on external services like node balancers, that can't run a client directly.

**Comment by OlafLostViking** [comment]
That would be great! And also make them manually callable like other steps.

I am currently trying to get my certificates via a script that uses `sftp` and `ssh systemctl` onto the servers by misusing the `services` setting - acmebot is running on another computer. But I cannot trigger that manually when acmebot thinks all is well (which obviously wasn't - bad for script developing/debugging ;-) ).

Thanks!

**Comment by OlafLostViking** [comment]
Another event should be `zone data updated`. I use `nsupdate` to let acmebot update zones on a remote server. But if I understand it correctly, it has to wait until _all_ NS in the zone are updated. So a way to force a AXFR would be nice (so we can write a script like `ssh DNS pdns_control notify ZONE`...).

**Comment by plinss** [comment]
If you have need of more hooks, or more data provided to a hook, please let me know.

**Comment by OlafLostViking** [comment]
Wow, great! Time to improve my python and delete the just finished shell script... ;-)

Thank you very much!

**Comment by plinss** [comment]
Note the hooks are called as separate executables, so they don't need to be written in python. The value of the hook is the command line called (apologies if that's not clear from the docs, will re-write).

**Comment by OlafLostViking** [comment]
Sorry! I misarticulated myself. Your description was clear! It's just that I thought I can now invest some time to make it "nice", now that no more ugly hacking is needed. Thank you - I'll try it out :)

**Comment by robbat2** [comment]
@OlafLostViking Can you share your hooks somewhere?

**Comment by plinss** [comment]
@robbat here's an example hook I use to update the TLS fingerprints for a matrix-synapse server:

in acmebot.json:
```
{
    ...,
    "hooks": {
        "certificate_installed": "/etc/matrix-synapse/fingerprints {certificate_name}"
    }
}
```

and then `/etc/matrix-synapse/fingerprints`:
```
#!/bin/bash

OUTFILE=/etc/matrix-synapse/conf.d/fingerprints.yaml
CERT=$1

if [ "matrix" == "${CERT%%.*}" ] ; then
	RSA_HASH=$( openssl x509 -in /etc/ssl/certs/${CERT}.rsa.pem -outform DER | openssl sha256 -binary | base64 | tr -d '=' )
	ECDSA_HASH=$( openssl x509 -in /etc/ssl/certs/${CERT}.ecdsa.pem -outform DER | openssl sha256 -binary | base64 | tr -d '=' )
	echo 'tls_fingerprints:' > ${OUTFILE}
	echo '  - "sha256": "'${RSA_HASH}'"' >> ${OUTFILE}
	echo '  - "sha256": "'${ECDSA_HASH}'"' >> ${OUTFILE}
	systemctl restart matrix-synapse
fi
```
