### ISSUE TITLE
no challenge added if "alt_names" is missing

### ISSUE THREAD

**Issue by OlafLostViking** [plinss/acmebot#18]
I understood (probably my fault ;-) ) the documentation so that `alt_names` is an optional setting if the certificate name/`common_name` is the only name needed in a certificate.

Now I just started trying out acmebot (so I'm surely making lots of mistakes...) and while all `certificates` entries (within an enclosing `private_keys` block) with `alt_names` got an acme_challenge added to the DNS via nsupdate, the only one missing `alt_names` wasn't added to the DNS server.

**Comment by plinss** [comment]
The `alt_names` should be optional, it defaults to `"<common-name>": ["@"]`. Note that this will put authorization DNS records in the `common-name` zone.

Can you give me a copy of the config file so I can try to reproduce locally? (feel free to redact anything sensitive)

**Comment by OlafLostViking** [comment]
I wish I could :-D

I'm currently learning letsencrypt/acme/acmebot and am changing stuff every minute. I'll try to remember your request when I stumble upon such a situation again.

**Comment by plinss** [comment]
Ok, I'm going to close this for now then as it appears to be working based on my testing. If you run in to the problem again, please re-open and add the config file.

Just to be clear, if you don't specify the `alt_names` it defaults to having a single `alt_name` with the same value as the `common_name` of the certificate (which itself defaults to the certificate name). So the minimal configuration:

    "certificates": {
        "example.com": {}
    }

is equivalent to:

    "private_keys": {
        "example.com": {
            "certificates": {
                "example.com": {
                    "common_name": "example.com",
                    "alt_names": {
                        "example.com": ["@"]
                    }
                }
            }
        }
    }

Which would attempt to get an authorization for "example.com" by placing the "_acme-challenge.example.com" TXT record in the "example.com" zone.
