### ISSUE TITLE
SCT not working

### ISSUE THREAD

**Issue by OlafLostViking** [plinss/acmebot#19]
No matter if I skip adding the `ct_logs` section from the documentation to my config or if I add it, `acmebot` gives this message for all certificates in the logfile:
```
Unable to retrieve SCT from log google_pilot HTTP error: 400 Bad Request
{
  "error_message": "Invalid Request.",
  "success": false
}
```

Further details aren't given, although I was calling `acmebot --detail`.

**Comment by plinss** [comment]
I've seen this when running against the staging environment (which is somewhat expected). Can you post a copy of your config file? (you shouldn't need to specify `ct_logs` as the defaults should cover LE and current browsers)

**Comment by cpu** [comment]
> I've seen this when running against the staging environment (which is somewhat expected).

Fwiw, for staging certificates you should be able to lookup SCTs from Test Tube (ct.googleapis.com/testtube).

**Comment by plinss** [comment]
Thanks @cpu, added Test Tube to the default list of CT logs in 2a73d50.

**Comment by OlafLostViking** [comment]
Oh! I'm sorry - my bad. I'm still only testing and therefore am still on staging only. It makes sense that these certificates aren't added to the log - I didn't expect the servers but the client to prevent that.

**Comment by plinss** [comment]
FWIW, while testing, now that the Test Tube CT log has been added, you can add:
`"ct_submit_logs": ["google_testtube"]`
to the `"settings"` section of acmebot.json and it should work.

**Comment by OlafLostViking** [comment]
Thanks - both modes are working wonderfully. Using the `google_testtube` with staging as well as the default entries when going productive.
