### ISSUE TITLE
check for permissions before setting file ownership

### ISSUE THREAD

**Issue by OlafLostViking** [plinss/acmebot#39]
When new files are created, _acmebot_ tries to set the ownership to `root:ssl-cert`. This will fail when it's not called as `root`.

I'm running it as a dedicated `operations` user which has no special rights locally. Luckily, _acmebot_ does not stop working. It's just "spaming" error messages.

*Suggestion:* The easiest solution I can imagine would be adding a configuration option with user and group name to assign the files to.

**Comment by plinss** [comment]
There already is a configuration option for file ownership:

    "settings": {
        "file_user": "root",
        "file_group": "ssl-cert"
    }

**Comment by OlafLostViking** [comment]
Oh! I'm so sorry - I guess I was still looking at an outdated local cloned README? Sorry for that - and thanks for your continued work on acmebot!
