### ISSUE TITLE
reload_zone_command is always called, also when only http confitmation is used

### ISSUE THREAD

**Issue by J0s3f** [plinss/acmebot#4]
I use a config where only http(s) is used for validation, meaning for every configured certificate a "http_challenges" entry exists.
Still, the command defined in "reload_zone_command" is always executed and the script then stops because it doesn't exist on my system. If I run acmebot again, it continues (with CT submissions).

As a workaround, I defined:

    "reload_zone_command": "/bin/true"

which allows the script to work without problems.

**Comment by plinss** [comment]
If remote DNS updates aren't configured, it's calling reload_zone after issuing certificate to give it a chance to update TLSA records. But, given that TLSA records are entirely optional, this shouldn't be a fatal error.

I made post-certificate change reload_zone non-fatal (will still generate a warning in verbose mode) and also allowed completely disabling reload_zone by setting the command to null or false.

Thanks for the bug report!
