### ISSUE TITLE
Default alt_names

### ISSUE THREAD

**Issue by sam0737** [plinss/acmebot#5]
Besides default common_name, can it have default alt_names too? Such that we could declare one cert as simple as
`
"certificates": { "example.com": {} }
`

**Comment by plinss** [comment]
I had considered it, but the issue is that I need to know which zone to place the acme challenge records in (for dns-01 authentication). I suppose a using the common name as the default zone, so your example would be equivalent to:
`"certificates": { "example.com": { "alt_names": { "example.com": ["@"] } }`
would work, does that work for you? (if using http-01 authentication then the zone doesn't matter anyway.)

**Comment by sam0737** [comment]
You are right that I am only on http-01.  The above syntax works and that's what I am using.
dns-01 is a hassle to do in my infrastructure setup.

(If there is a way to force all certificates to use http-01? so that I could get away with all the duplicated "http_challenges" entry 😄  )

**Comment by plinss** [comment]
Ok, will add the default.

There's not currently a way to force http-01, you just have to set a challenge directory for each domain name so it knows where to put the challenge files. Regarding duplication, do you have multiple domain names that are all served from the same directory?

**Comment by sam0737** [comment]
I configured my load balancer frontend (which will also terminate the SSL) to serve all the .well-known/acme-challenge request from a single directory which acmebot write to.  

It's true that this setup might not be all that common.  

What if such http challenge global configuration is made like those entries in "directories" that accept parameters placeholder?

**Comment by plinss** [comment]
Not following what you mean about the parameters placeholder for the directory, can you give an example?

**Comment by sam0737** [comment]
```
"directories": {
  "http_challenges": "/var/www/{name}/.well-known/acme-challenge"
}
```
Configuration like this - might be enough for most scenario

**Comment by plinss** [comment]
I added a "http_challenge" directory per your suggestion in 179ac28 (used singular to match other directory names). You can use {zone}, {host}, and {fqdn} fields.

Note that you can override individual domains for dns-01 authorizations by also setting a "http_challenges" entry with a null value.
